/**
 * THE APPROVED PACING, in seconds of real silence.
 *
 * Auto-generated by `npm run voiceover:plan -- --snapshot` from the approved
 * cut. These are the numbers that should survive a voice change: how long the
 * narrator waits before starting a scene, between thoughts inside it, and
 * before the scene ends.
 *
 * They are measured speech-to-speech - each clip's own leading and trailing
 * silence is excluded - so they mean the same thing whichever engine produced
 * the audio.
 *
 * A scene marked `silent` has no narration; its duration is kept as-is.
 */
export interface ScenePacing {
  id: string;
  /** Scene start -> first word. */
  leadIn?: number;
  /** Silence between consecutive phrases, in order. */
  pauses?: number[];
  /** Last word -> scene end. */
  tail?: number;
  silent?: boolean;
  duration?: number;
}

export const pacing: ScenePacing[] = [
  {
    "id": "hook",
    "leadIn": 0.353,
    "pauses": [
      0.622
    ],
    "tail": 0.745
  },
  {
    "id": "old-cycle",
    "leadIn": 0.338,
    "pauses": [
      0.632
    ],
    "tail": 0.799
  },
  {
    "id": "today",
    "leadIn": 0.376,
    "pauses": [
      0.713,
      0.479
    ],
    "tail": 1.046
  },
  {
    "id": "the-change",
    "leadIn": 0.337,
    "pauses": [
      0.666
    ],
    "tail": 1.186
  },
  {
    "id": "april",
    "leadIn": 0.336,
    "pauses": [
      0.561
    ],
    "tail": 0.8
  },
  {
    "id": "march",
    "leadIn": 0.505,
    "pauses": [
      0.582
    ],
    "tail": 0.805
  },
  {
    "id": "no-change",
    "leadIn": 0.337,
    "pauses": [
      0.565,
      0.431
    ],
    "tail": 1.082
  },
  {
    "id": "example",
    "leadIn": 0.406,
    "pauses": [
      0.509,
      0.71,
      0.652,
      0.548,
      0.706
    ],
    "tail": 0.976
  },
  {
    "id": "summary",
    "leadIn": 0.46,
    "pauses": [
      0.609
    ],
    "tail": 1.056
  },
  {
    "id": "why",
    "leadIn": 0.354,
    "pauses": [
      0.527,
      0.387
    ],
    "tail": 0.648
  },
  {
    "id": "close",
    "leadIn": 0.502,
    "pauses": [
      0.391
    ],
    "tail": 1.379
  }
];
