/**
 * MEASURED VOICE-OVER DURATIONS (seconds), keyed by voice-line id.
 *
 * Auto-generated by `npm run voiceover:build` from the rendered audio, so that
 * captions land exactly on the narration. If you supply your own recording,
 * re-run that script (or edit these numbers by hand) to re-sync the subtitles.
 */
export const measuredDurations: Record<string, number> = {
  's1-l1': 2.218,
  's1-l2': 1.242,
  's2-l1': 3.669,
  's2-l2': 2.821,
  's2-l3': 1.451,
  's3-l1': 3.727,
  's3-l2': 3.82,
  's3-l3': 1.509,
  's4-l1': 2.554,
  's4-l2': 1.567,
  's4-l3': 1.393,
  's4-l4': 1.358,
  's4-l5': 1.416,
  's5-l1': 4.063,
  's5-l2': 2.728,
  's5-l3': 2.601,
  's6-l1': 2.264,
  's6-l2': 1.916,
  's6-l3': 1.707,
  's7-l1': 2.763,
  's7-l2': 3.309,
  's7-l3': 1.823,
  's8-l1': 1.254,
  's8-l2': 2.264,
  's8-l3': 2.252,
  's8-l4': 1.068,
  's8-l5': 2.02,
  's9-l1': 2.392,
  's9-l2': 3.146,
  's10-l1': 2.136,
};
