/**
 * MEASURED VOICE-OVER DURATIONS (seconds), keyed by voice-line id.
 *
 * Auto-generated by `npm run voiceover:build` from the rendered audio, so that
 * captions land exactly on the narration. If you supply your own recording,
 * re-run that script (or edit these numbers by hand) to re-sync the subtitles.
 */
export const measuredDurations: Record<string, number> = {
  's1-l1': 2.508,
  's2-l1': 4.191,
  's2-l2': 5.492,
  's3-l1': 4.238,
  's4-l1': 4.957,
  's5-l1': 5.097,
  's5-l2': 2.682,
  's5-l3': 4.923,
  's6-l1': 4.702,
  's6-l2': 4.946,
  's7-l1': 2.426,
  's7-l2': 3.483,
  's8-l1': 4.365,
  's8-l2': 3.553,
  's9-l1': 2.868,
};
