/**
 * MEASURED VOICE-OVER DURATIONS (seconds), keyed by voice-line id.
 *
 * Auto-generated by `npm run voiceover:build` from the rendered audio, so that
 * captions land exactly on the narration. If you supply your own recording,
 * re-run that script (or edit these numbers by hand) to re-sync the subtitles.
 */
export const measuredDurations: Record<string, number> = {
  's1-l1': 4.272,
  's1-l2': 4.026,
  's2-l1': 2.028,
  's3-l1': 2.115,
  's4-l1': 4.184,
  's5-l1': 4.45,
  's5-l2': 6.931,
  's6-l1': 4,
  's6-l2': 5.221,
  's7-l1': 3.425,
};
